### ISSUE TITLE
Choice of value for A/V sync requirement in DPCTF spec and testing

### ISSUE THREAD

**Issue by cta-source** [cta-wave/device-playback-task-force#100]
The question in this issue is, **what should be our A/V sync requirement in terms of +X/-Y mS?**

Jan Mueller highlighted this document: [Rec. ITU-R BT.1359-1 1 Relative Timing of Sound and Vision for Broadcasting](https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.1359-1-199811-I!!PDF-E.pdf])
He notes that this document indicates that there is detectability at the point of +45/-125ms. He also indicated that Dolby's requirements are in that region as a combination of this EBU rec and streaming partner input, and in the range of **+40/-120 mS**.
 
However, the current proposed requirement for AV sync is "+/-20 mS" (see dpctf-s00001-v032-WAVE-DPC-v1.20.docx, section 9.2). 

I chose this value entirely based on the observation window size ("resolution") of the audio white noise code in [last year's audio 'watermark' study project](https://github.com/cta-source/audio-watermark-study). That code takes a 20 mS block of predetermined pseudo-random noise (PRN) and finds where that block is embedded in our test vectors. The observation window size is "slop" in the measurement, meaning we get at best a +20 to -20 mS measurement of a value.

So the proposed +/-20 value is 1) too tight, implying hitting +/-0 mS _before_ the observation window tolerance; and 2) too tight compared to the EBU Rec information and Dolby experience.

We can pick a better fundamental spec number like +40/-120, but we're stuck with resolution issues due to the observation window.

That 20 mS observation window is enough to give -13 dB audio SNR. Audio SNR is defined here as the ratio of PRN 'signal' to any added noise in our test setup. It's a negative number, meaning the system noise (people talking in the background, music, etc.) can be 13 dB higher than the PRN signal. (The pseudo random noise is the signal, the added music or what not is noise, in this SNR.)

 _(As an aside: Ambient room noise and wall echoes dominate noise considerations when testing with mic/speakers. Hardware noise is de minimis even when using microphone and speakers. Wire-connected systems have no measurable noise in my setup, which is two laptops connected by line cable and USB-to-audio adapters.)_

Some options for consideration while choosing an A/V sync requirement value for WAVE:

_Use a tighter observation window_
The current audio PRN code operates well with 13 dB SNR margin. The '-13' can be derived mathematically and is observed in testing, so that's pretty much our starting point. A factor of 2 in observation window is 3 dB in SNR. We can play with this as in, 

- 20mS resolution --> 13 dB SNR in test environments
- 10mS resolution --> 10 db SNR
-   5mS resolution -->   7 dB SNR

I'd be uncomfortable under 10 dB SNR due to echoes (with mic/speakers). It's possible to tell your lab buddies to shut up and turn off the music, but echoes are more problematic. (10 dB implies the echo can be 10x power of the direct path signal; this condition can be met by multipath. At 13 dB I had no problem in a rather worst-case room, so 10 dB "should" be OK.) Audio experts with in-room multipath experience, any input on instantaneous or sustained peak levels?

_Allocate the tolerance differently_
There is a question of where to place the tolerance burden, on the streamer or on the test. We could tighten or loosen the spec by our resolution, depending on whether w choose to make the streamer (or player, etc.) responsible for the difference, or absorb it ourselves. 

_Parameterize the observation window and let test operators choose_
Finally, we could parameterize the resolution. For example, set "+40 / -120 mS" as the spec and default to 10 mS resolution _but_ allow for 5 mS and 20 mS. 

_My suggestion_: Pick our 'desired' value of +X/-Y, like +40/-120. Absorb resolution delta in our test, so that a +50/-130 mS result could potentially pass, but we'd avoid false negatives. This approach would get something working with the current (tested) study project code. Consider parameterization for a later enhancement. 

Thoughts?

**Comment by haudiobe** [comment]
DPCTF 2022/06/29
- We should verify that no misalignment is added in our processing (encoding and packaging) of the content. If this is the case, our content can be used as an accurately synced anchor - please respond, if you have any different opinion.
- Hence, we could add all tolerance to the device as mentioned above. However, in practical applications misalignment may already have happened upstream in distribution and production. Hence, we may consider to require that the tolerances for the device are smaller than what the ITU-R recommendation provides for end-to-end performance. Input from production and distribution experts would be welcome. We will ask the twg and cstf if they have any input on this matter.
- Until we receive no feedback, it is suggested to add the full tolerance from the ITU spec to the DPC specification, but also add a NOTE that would clarify this assumption (i.e. no misalignment of the content ever happens).

**Comment by wschidol** [comment]
> I chose this value entirely based on the observation window size ("resolution") of the audio white noise code in [last year's audio 'watermark' study project](https://github.com/cta-source/audio-watermark-study). That code takes a 20 mS block of predetermined pseudo-random noise (PRN) and finds where that block is embedded in our test vectors. The observation window size is "slop" in the measurement, meaning we get at best a +20 to -20 mS measurement of a value.

I think this is not entirely correct. The 20 ms have an influence on the SNR (and hence reliability of the measurement). Additionally if 20 ms is the repetition rate of the measurement then changes of latency can't be picked up quicker than within 20 ms. However, when the latency is found through crosscorrelation then it can be accurate to a sample (assuming no noise)!

What I take from that is that there is no need to add the 20 ms blocksize to whatever latency limits we decide on.

**Comment by pshorrock** [comment]
[Note this might be jumping the gun a bit but it is perhaps a good idea to think about the end goal with respects to testing - apologies, bit of a brain dump / initial thoughts.] 

We (Eurofins) would need to respond again with more specific information but when looking at this from a testing rather than a specification perspective we see tolerances in the video representation capture which can be influenced by the frame rate, screen refresh and clarity of the QR code which could lead as a minimum to video frame times drifting (we have seen this today and have had to add tolerances). We also see tolerances in the camera synchronising the audio and video (it's doing the heavy lifting but can we trust it?) and as Mike has mentioned in the accuracy we put into the audio itself when creating the mezzanine. This leads us to the question of will it be possible to automatically test the AV sync and be confident there are no false negatives (more likely to flag as an issue than a few false positives in a string of negative results), or will there be a need to find a way to smooth this out in the results where an average of points is taken and it is not failed for a single frame appearing to not be synchronised. To go the the point: would this discussion inevitably come back to the perceptual AV Sync tolerance (presumably it can't be bigger than this?) which treats the delivery infrastructure as a black box and will a means to test the test and an early prototype be important to check the end goal is achieved, which is presumably 'is the users experience satisfactory or is there any perceptual misalignment of AV sync'? I just wonder if as a group we would be happy trusting just maths with so many variables on a topic which humans are very good at detecting. Is ultimately the end result (if we follow ITU) the device must present the content within the 40/120ms (regardless of where tolerances may be stacked up as going outside of this would be detectable) and the testing environment needs to show comparable results to a manually detectable audio track (tears of steel) with the same video track, where potentially we could force a misalignment of the media input tracks (validate more than just the happy path). My overall concern is with so many different potential tolerances will a complex approach / definition leave it open to too many challenges when validating/testing? Ultimately this needs to be robust and of value and to do that I think we need to find a way to remove some of the complexity in the way we describe it (I think that is where you were heading initially @cta-source  ? If so that is the approach we would support).

**Comment by cta-source** [comment]
@pshorrock, I think we're on similar tracks. We start with the assumption that the CMAF content is correctly aligned. As the device-under-test (DUT) plays it back, we have DUT-induced drift, tolerances in the camera, 20mS resolution swing in the audio sync, and maybe things we're not considering yet. 

On the whole, I believe we need experience with the A/V sync implementation. I'd previously found one issue, clock skew between the DUT and the OF computer. The audio sync code compensates for clock skew now, but it is an example of these measurement tolerances (as opposed to the purity of maths!) 

Net--we should start somewhere, like +40/-120, and learn from it. And until we can answer these questions more clearly, perhaps A/V sync mismatches should be flagged as 'warnings' rather than 'errors'.

**Comment by haudiobe** [comment]
DPCTF Call 2022/07/13:

We decided to:
1) go with 40/120 with reference to ITU spec
2) add a note that this is the most agreeable value (based on ITU spec), but the tests can be executed with other parameters as well in case someone has specific domain knowledge for the test.
3) Test framework implements such a parametrization

@cta-source will add this to the specification to v1.22 as available on workspace.

**Comment by mbergman42** [comment]
@haudiobe , done. Please see the new v1.23. Please close this issue.

**Comment by gitwjr** [comment]
Resolved. Documented in spec. It is +40/-120ms. Close.

**Comment by gitwjr** [comment]
Resolved. Documented in spec. It is +40/-120ms. Close.
