### ISSUE TITLE
Accuracy of value returned by HTMLMediaElement.currentTime

### ISSUE THREAD

**Issue by wilaw** [cta-wave/device-playback-task-force#28]
This is a former User Agent Integration Spec issue which has been assigned to DPCTF.

**Comment by jpiesing** [comment]
The title is a bit misleading - the real issue is where is currentTime measured in the media pipeline?
- The output of either the video or the audio decoder?
- Where graphics and video are composited?
- What is sent over an HDMI interface (where applicable)?
- What the user sees?

I asked about this in whatwg and got an answer from someone from Firefox - https://github.com/whatwg/html/issues/3041

**Comment by jpiesing** [comment]
The original issue is here - https://github.com/w3c/webmediaporting/issues/9

**Comment by jpiesing** [comment]
This one is also closely related - https://github.com/w3c/webmediaporting/issues/24

**Comment by poolec** [comment]
To my mind, the primary purpose for currentTime is to be able to take some action, the result of which would typically cause a change to the graphics or video being displayed to the viewer.  For this use case, any delay that is common to both graphics and video (e.g. picture processing delay) should not be taken into account.  If it were, then any attempt by the application to make something appear or change on screen at a particular point in the media timeline would always be delayed by the picture processing delay.

That's not the only use case though.  An app could be using the current time to communicate to another device for synchronisation purposes.  In that case the app would be more interested in the media on the screen.

Since there is only one 'currentTime', I think the option "Where graphics and video are composited" makes most sense.  It would be desirable if the device could separately indicate its best estimate of any picture processing delay.

**Comment by haudiobe** [comment]
19/02/13 (DPCTF): W3C API - HTML5 does not accurately define the work. 
If no updates by end of March 27, 2019, this bug will be closed w/o any action.
