### ISSUE TITLE
Minimum graphics performance for rendering images, animations and video

### ISSUE THREAD

**Issue by wilaw** [cta-wave/device-playback-task-force#30]
This is a former User Agent Integration Spec issue which has been assigned to DPCTF.

This issue relates to 

1. the Minimum graphics performance necessary to decode & rendering full screen video, images, CSS3 animations, etc
2. Correct scaling of video, both in page and at fullscreen.

**Comment by jpiesing** [comment]
The HbbTV work on minimum graphics performance is derived from https://github.com/Orange-OpenSource/orangemark .

Since the goal was to set a bar that could be met by any device where the browser was actually connected to the hardware graphics acceleration, the usual shortcomings of benchmarks didn't apply.

The benchmarks were run on a variety of devices and values picked which would only broken implementations would fail to meet.

**Comment by jpiesing** [comment]
The original issue is here https://github.com/w3c/webmediaporting/issues/20

**Comment by haudiobe** [comment]
19/02/13 (DPCTF): expands scope - so we should get mandate and supporting companies from TWG.

**Comment by haudiobe** [comment]
2020/07/08 f2f: no support
