### ISSUE TITLE
Low-Latency: Short Buffer Playback

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#78]
Background: In low-latency, typically playback is done based on only a short buffer duration.

CMAF Content: Create CMAF Chunked content with chunk durations in the range of Low-Latency playback

Stimulus: Fill chunk by chunk on a frequent basis

Expected Playout Behaviour: It works

**Comment by haudiobe** [comment]
Check if this test is already documented

**Comment by jpiesing** [comment]
The AVC content options (https://1drv.ms/w/s!AiNJEPgowJnWgbpZesbLvglzCXVlSg?e=4ZFRyB) say the following.
> CMAF Fragment durations
> o 2 seconds
> o 5 seconds

Is this what you mean?

**Comment by dsilhavy** [comment]
Again might need to consider minimum buffer level required on specific platforms. If a CMAF chunk corresponds to a single frame multiple chunks might be required for playback to start. Consequently, playback might stall for different platforms at different buffer levels.

**Comment by jpiesing** [comment]
Suppose an implementation requires a minimum of (say) 5s buffered and will stall when the buffer size drops below that. That's clearly not a low latency enabled implementation. Is it surprising if it would fail such a test?
The test could be made configurable so that particular content providers could require the test to be passed with at least a certain value in order to have access to their content.

**Comment by dsilhavy** [comment]
> Suppose an implementation requires a minimum of (say) 5s buffered and will stall when the buffer size drops below that. That's clearly not a low latency enabled implementation. Is it surprising if it would fail such a test?
> The test could be made configurable so that particular content providers could require the test to be passed with at least a certain value in order to have access to their content.

I like that approach

**Comment by haudiobe** [comment]
part of new test cases.
