### ISSUE TITLE
8.6: Explicitly calls out chunked content, what about 8.2-8.5?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#82]
8.6 explicitly calls out chunked content but 8.2-8.5 don't mention this. What is intended for 8.2-8.5?

**Comment by jpiesing** [comment]
Similarly 8.7 calls out chunked playback and 8.8 onwards to the end do not. Some explicitly mention fragments which presumably means the content doesn't have to be chunked? Some mention neither.

**Comment by haudiobe** [comment]
8.6 is playback of chunked content by adding chunk by chunk.

8.7 is quite different. Give me anything be it fragmented or chunked content.
- Fraunhofer used chunked content and concatened and resplit the content at random positions
- One could also use regular content and resplit the content at random positions. Not needed.

8.6 is only done with chunked content.
For every other test, we should define if it needs to be done with chunked content only, fragmented content only, or both.

8.6 is 8.2 with chunked.

8.3, 8.4 and 8.5 could also be done with chunked content.

We add a sentence that fragmented content unless otherwise specified.

**Comment by gitwjr** [comment]
@haudiobe 
Add text at the beginning that if not explicitly mentioned, fragmented content is used, not chunked content.

**Comment by gitwjr** [comment]
Clarifying text was added to clause 8.1 in v1.38 and revised in v1.39 of DPCTF spec. "For content, if not mentioned otherwise, fragmented content is used and not chunked content. If chunked content is to be used, the test is explicitly stating this."
