### ISSUE TITLE
Can tests assume an audio output socket connected to a camera?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#89]
There's a discussion in https://github.com/cta-wave/mezzanine/issues/34#issuecomment-858642919 and following about using the white noise audio mezzanine content for testing a/v sync instead of flashes and beeps.

If the device to be tested doesn't have a headphone out or similar then the white noise may be disturbing to listen to unless the volume is turned down. Even if not disturbing, it could certainly be annoying.

Can we assume that ;
- most devices will have some kind of wired audio output plugged into the input on a camera and
- it's OK for devices without a wired audio output to play white noise through the speakers?

@haudiobe Please can this be on the agenda for the next DPCTF call?

@yanj-github
@nicholas-fr

**Comment by pshorrock** [comment]
Many thanks for raising this @jpiesing. To add a few more (hopefully) useful comments from our side - where we can only really base that on what we see today and very much needs the wider group to help with the future view:
* While working on audio capture for a different testing regime we have found some TVs which do not have a 3.5mm audio jack output. This is not all devices and we do not know how prevalent this may become. There are potentially other options; HDMI out (though we tend to not see this on TVs), S/PDIF etc that *could* be viable to get a wired audio connection but we have not yet explored or proven this could be relied upon. Therefore we believe unless someone else can state anything with more authority that it is conceivable that a TV may be presented for testing which requires microphone capture. Input from the group would be very much welcomed to understand roughly what percentage of devices may fall into this category (or if another viable way to work around this to get a wired connection is known that would not compromise the testing setup)
* For personal devices (phone, tablet, computer) it would appear that USB to 3.5mm, USB-C to 3.5mm and lightning to 3.5mm adapters exist. We have not tested these nor if they would work sufficiently well but their existence suggests it *should* be possible to capture the audio unless devices are due to stop supporting wired connections to headphones. We have not investigated this further and again would welcome the views of the group as to how likely in future this may be.

**Comment by wschidol** [comment]
AFAICS, the benefits of having a wired connection over microphone capture are

* better SNR giving more robust test results
   * no lab noise spilling into recorded signal
   * results not tainted by speaker, microphone, and room impulse/frequency response
* possibly less reliance on a specific high-quality type of gear
* less annoyance to test personnel

Note that our own testing indicates that the noise method can work with microphone capture in noisy (no pun intended) environments, and can tolerate less-than-ideal speaker and microphone responses, though there are certainly limits to both.

While white noise can be considered annoying (depending of course on its volume), beeps and sine tones are possibly no less annoying. The alternative is to build a test that not only can, but *must* be observed by humans, and is not automatable.

**Comment by nicholas-fr** [comment]
I believe most TVs have at least 1 audio output (headphones out, S/PDIF or HDMI ARC). 
TV digital outputs could be connected to the camera via an audio system if needed.
However, that may add unwanted additional complexity to the setup (e.g. digital output format and audio delay considerations). With careful configuration it would be fine, but any additional configuration is something more that can go wrong.

**Comment by ZmGorynych** [comment]
There is commercial software which can test for lip sync on natural video,
w/o requiring specific sequences.

**Comment by jpiesing** [comment]
I think the conclusion of the discussions is that a wired connection between the device and the camera is strongly recommended but that use of speaker + microphone still needs to be possible. We may explore options to mitigate the poor operator experience when using speaker + microphone but the success or failure of those explorations won't change the conclusion.
If so then I think we just need to add something to the documentation & we can close this issue.

**Comment by haudiobe** [comment]
DPC Editing call: We should add some test environment description in the spec, potentially be reference. For example a reference test environment with a camera, an audio output and so on. Possibly along with the mezzanine content description. Can the DPC Test group provide this, possibly using existing documentation. or do we have a reference?

**Comment by andyburras** [comment]
`DPC Editing call: We should add some test environment description in the spec, potentially be reference. For example a reference test environment with a camera, an audio output and so on. Possibly along with the mezzanine content description. Can the DPC Test group provide this, possibly using existing documentation. or do we have a reference?`

We could add a reference to:
https://github.com/cta-wave/device-observation-framework#obtain-recording-files
I would propose keeping it in the github, and then we can easily add additional instructions and clarifications based on users' experiences and feedback.

**Comment by haudiobe** [comment]
DPCTF Call Dec 15, 2021: add a simple prose description of an envisaged environment. High-level.

**Comment by haudiobe** [comment]
DPCTF Call Jan 26, 2022: No further comments. Hence we agree to implement accordingly.

**Comment by gitwjr** [comment]
Resolved. Text added to DPCTF Deploy with a note that it applies to Phase 1. Phase 2 camera definition is TBD. No change to spec. Closed.
