### ISSUE TITLE
The issue of “multiple codecs in parallel” needs further discussion.

### ISSUE THREAD

**Issue by cta-source** [cta-wave/device-playback-task-force#9]
_Captured from 2016-08-17 DPCTF meeting discussion_
This was stated as a goal but not fully defined.

**Comment by KilroyHughes** [comment]
Most video ads in Web pages have historically used their own video element, often a plugin like Flash, and allowed streaming a video program in a different format, protocol, etc. in a separate element. An ad can be displayed full screen or in a window, and return to a live program at any time. A short ad can be downloaded as single file, and need not match the format, codec, encoding parameters, or timing of the program media element. A modular ad "player" is required for other functions, such as authentication, authorization, targeting, and playback verification, so is often a standard ad plugin provided by an ad network for use in many different players, protocols, and programs.  Internet streaming ads are typically not encoded and "splice conditioned" to match each program they appear in. Separate ad and program media elements enable independently encoded, delivered, and measured ads and programs, and eliminate "splice conditioning" constraints caused by a single media element. Depending on Device architecture, software decoding of a second video element may be necessary when hardware video acceleration is only possible on the program media element. 

WAVE could specify tight splice condition constraints for single element playback, but support common practice, ad networks, etc. using two elements and minimal splice conditions.
