### ISSUE TITLE
within the tolerance of the sample duration.

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#94]
The DPCTF spec says this a lot;

> The presented sample matches the one reported by the currentTime value within the tolerance of the sample duration.

What is "the sample duration"?
- Is "sample" here the sample concept from ISOBMFF which causes so much confusion in audio?
- For video, is this one frame?
-

**Comment by haudiobe** [comment]
DPCTF 21/10/20:

sample is meant to be the sample according to ISO BMFF, i.e. in case of the test content, it would be the inverse of the `@timescale `value assigned to the CMAF Track.

This value may be too strict, currentTime may be less accurate. Another value may be provided. 

Proposal to fix:
- currentTime accuracy 2/timescale (i.e. 2/framerate) +- 20ms for video
- for audio this is still tbd => open up new issue for audio @cta-source

**Comment by yanj-github** [comment]
Thanks @jpiesing  and @haudiobe,
Do you mean currentTime accuracy tolerance is: 2/timescale (i.e. 2/framerate) + 20ms for video?

**Comment by cta-source** [comment]
```
Proposal to fix:

- currentTime accuracy 2/timescale (i.e. 2/framerate) +- 20ms for video
- for audio this is still tbd => open up new issue for audio @cta-source

```

Accuracy of audio time measurements on playback streams was discussed here: [Mezzanine/Issues/What is the right resolution time period for audio testing? #44](https://github.com/cta-wave/mezzanine/issues/44#issuecomment-924971203) (closed issue)

The resolution is,
`...we need to stay on 20mS until we cannot support a required test environment. If speakers/mic/music/room noise really is not feasible at 20mS, we can reassess. Recommend closing this issue and continuing with the current path of developing 20mS wired-only tests first, and continuing to study opportunities for speaker/mic/music/noise.`

I believe this information should close the audio half of this Issue, of course there's still a question about video.

**Comment by ZmGorynych** [comment]
Note that timescale is not mathematically related frame rate, at least not
in US. E.g. 240KHz, 90KHz, or 60KHz are fairly reasonable timescale values
for multiple frame rates.

Audio is also interesting, sample duration for AAC is different from E-AC-3

**Comment by cta-source** [comment]
> Audio is also interesting, sample duration for AAC is different from E-AC-3  

This audio sample duration is currently an input parameter for the automated tests.  We are free to put a parameter in a config file upstream.  Are you suggesting we should do that?  The current 20mS value is pushing the limits of the watermark technology, so if we're going lower than 20mS, it would be good to know now.

Note that there are functional differences between using the natural sample rate of the codec and using the sample rate of the automated test.  Because the automated test is working from analog output, not encoded audio, the OF will not know how to synchronize the test to the actual audio frames.  The actual audio framing is only available on the device under test, not the OF computer, in DPCTF.  

We're currently using this approximation: If we are looking for out-of-order segments of audio, then simply checking that _each 20mS is in approximately the correct place_ (within 1% or so, more on this below), then out-of-order playback errors will be obvious as long as the encoded sample period is not significantly shorter than 20mS (specifically, half that, and even then we'd need somewhat bad luck to miss an error).  

On the accuracy of 1%, there is a different question of playout timing accuracy: jitter.  Right now, the "research project demo" is rounding off errors due to sample clock rate differences.  A 300ppm difference between the device under test and the OF computer accumulates an error of about 1 audio sample period (1/48kHz) error every few 20mS samples.  Any playout jitter aside from this will also be rounded off and not caught, at this time.  

It is reasonable to talk about solutions to this uncaught jitter consideration.  We could measure the overall clock rate delta, compensate, then look at playout jitter accuracy after this compensation, but that's not in there yet.  

In the DPCTF spec (the required audio observations), I don't see this "maximum jitter" called out as a requirement yet.  Those requirements -- so far -- appear to call for audio segments to be played in the right order (with respect to other segments, and separately with respect to currentTime).  But limiting playout jitter (meaning, the specific sample starts "on time" +/- a maximum jitter value) isn't called for.  Willing to be convinced otherwise.

**Comment by haudiobe** [comment]
DPC Editing v1.0.8 implements this for audio and video. Needs to be added for every observation.
